language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
script:
- "./gradlew testDebugUnitTest"
- "./build-apk.sh"
notifications:
  slack: lp-iem:kDPhwslAWdRY6xk89yHqyL9i
branches:
  only:
  - master
  - develop
deploy:
  provider: releases
  api_key:
    secure: if/rSTn9mBdtx2KJ7QEtIOPm9DzdFbAcPpAvZbpcBQLdN117oHIpfqF8CJ3RaxX9PA6PVqvT98YlUe7QqsgrsS8a+kFC68Tinb6dR41shooiqXjfmhF1Ap3IT3ArHJH3+S4k9RdE+aMSdBzjdteu2Oc2JD1wWNIQ9wly/G/LPPFecKyCRNuZA7h+V9JOwoHO1S6HAfVjvwWf+Z2swzSLZZWUobvvz8O+jI4dBtv3C33fHXVVBYv6uWdr0TjdYT+/0GNxi7xIBlwLigiVNWn3q/kbvZOhSZ5FevkM6m/DDsMvmdCWUlUcro8vixqZ9wHEUdSds660/8b5a35dlIlzihTJWMT8/1Bm4e6tZw+jNvM8yO2rFb08Ti5PKKM0wJaD3kKwxiR/STF6YMZhF+G8rujowdOYSlLgSC9ww0D5ONGc8Q+JLVls8h84I2up0om7tnjo8YkOx1X55/1m5tSIer9szGa2LzkHqW4h5+MsrXqDmtwEmlca+dodlEImMgYI5scgDIcn7mixv5b3enTt78Co7r2BNOcgN1xq5EgZwlAeBjtwaZN1kYfBPs6SMEUI+yoJhvgcYIGcPkG+G5aFtajGHPsBn7Q64TdtBzkKny9Q3sFgITm/YNzlMXh3IsIGP18cLa0Q8Cgir8VtC+DyliTRX8Neua40oyB9ZLYnse8=
  file: "./build/apk/Comics.apk"
  file_glob: true
  skip_cleanup: true
  on:
    repo: RayanMehdi/TestProjetTravis
